line-length = 88
indent-width = 4

target-version = "py39"

[lint]
extend-select = ["I"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
// Modified on Tue Jan 21 11:33:40 PM +01 2025
// Modified on Tue Jan 21 11:33:41 PM +01 2025
// Modified on Tue Jan 21 11:33:44 PM +01 2025
