[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"// Modified on Tue Jan 21 11:33:42 PM +01 2025
// Modified on Tue Jan 21 11:33:48 PM +01 2025
// Modified on Tue Jan 21 11:33:59 PM +01 2025
